let items = [];
let batches = [];
let transactions = [];
let soData = [];
let openings = {};
let draftOrders = [];
let currentPage = 'dashboard';

document.addEventListener('DOMContentLoaded', async () => {
    await initDB();
    await loadAllData();
    renderAll();
    setupDateInputs();
});

async function loadAllData() {
    try {
        items = await db.getItems();
        batches = await db.getBatches();
        transactions = await db.getTransactions();
        soData = await db.getSO();
        const openingList = await db.getOpenings();
        openings = {};
        openingList.forEach(o => openings[o.itemId] = o.qty);
        draftOrders = await db.getDraftOrders();
    } catch (error) {
        console.error('Load data error:', error);
        showToast('Gagal memuat data!', 'error');
    }
}

function renderAll() { renderDashboard(); renderMaster(); renderTransactions(); renderBatches(); renderSO(); renderOpenings(); renderDraftOrders(); populateSelects(); updateSoSystem(); }

function renderDashboard() {
    const total=items.length, raw=items.filter(i=>i.category==='Raw Material').length, merch=items.filter(i=>i.category==='Merchandise').length, low=items.filter(i=>getCurrentStock(i.id)<5).length;
    const today=new Date(), nextWeek=new Date(today); nextWeek.setDate(today.getDate()+7);
    const expiring=batches.filter(b=>{const exp=new Date(b.expireDate);return exp>=today&&exp<=nextWeek&&b.qty>0;}).length;
    const todayStr=today.toISOString().split('T')[0], soToday=soData.filter(s=>s.date===todayStr).length;
    document.getElementById('totalItems').textContent=total; document.getElementById('totalRaw').textContent=raw; document.getElementById('totalMerch').textContent=merch; document.getElementById('totalLow').textContent=low; document.getElementById('totalExpire').textContent=expiring; document.getElementById('totalSO').textContent=soToday;
    renderRecentActivity(); renderChart();
}

function renderMaster(search='', category='all') {
    const container=document.getElementById('masterList'); let filtered=items;
    if(search){const s=search.toLowerCase();filtered=filtered.filter(i=>i.name.toLowerCase().includes(s)||(i.sku&&i.sku.toLowerCase().includes(s)));}
    const catSelect=document.getElementById('filterCategory'); if(catSelect&&catSelect.value!=='all') filtered=filtered.filter(i=>i.category===catSelect.value);
    if(!filtered.length){container.innerHTML='<div class="empty-state">Belum ada item</div>';return;}
    container.innerHTML=filtered.map(item=>{const stock=getCurrentStock(item.id),stockClass=stock<3?'critical':stock<10?'low':'';const img=item.image||'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="%2364748b" stroke-width="2"%3E%3Crect x="2" y="7" width="20" height="14" rx="2" ry="2"/%3E%3Cpath d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/%3E%3C/svg%3E';return `<div class="item-card"><img class="item-thumb" src="${img}" alt="${item.name}"><div class="item-info"><div class="item-name">${item.name}</div><div class="item-sku">${item.sku||'No SKU'} • ${item.category}</div><div class="item-sku">${item.uomBesar||'-'} → ${item.uomKecil||'-'} (1:${item.konversi||1})</div></div><span class="item-stock ${stockClass}">${stock}</span><button class="tx-delete" onclick="deleteItem(${item.id})" title="Hapus">🗑️</button></div>`;}).join('');
}

function renderTransactions(){const inList=document.getElementById('inList'),outList=document.getElementById('outList');const inTx=transactions.filter(t=>t.type==='IN').sort((a,b)=>b.id-a.id),outTx=transactions.filter(t=>t.type==='OUT').sort((a,b)=>b.id-a.id);inList.innerHTML=inTx.length===0?'<div class="empty-state">Belum ada transaksi IN</div>':inTx.map(t=>renderTxItem(t,'IN')).join('');outList.innerHTML=outTx.length===0?'<div class="empty-state">Belum ada transaksi OUT</div>':outTx.map(t=>renderTxItem(t,'OUT')).join('');}
function renderTxItem(tx,type){const item=items.find(i=>i.id===tx.itemId),name=item?item.name:'Item dihapus',sign=type==='IN'?'+':'-',cls=type==='IN'?'in':'out';return `<div class="tx-item"><div class="tx-info"><div class="tx-name">${name}</div><div class="tx-detail">${tx.note||'-'} • ${tx.date?new Date(tx.date).toLocaleString():new Date(tx.id).toLocaleString()}</div>${tx.batchId?`<div class="tx-detail">Batch: ${tx.batchId}</div>`:''}</div><span class="tx-qty ${cls}">${sign}${tx.qty}</span><button class="tx-delete" onclick="deleteTransaction(${tx.id})">✕</button></div>`;}
function renderBatches(){const container=document.getElementById('batchList'),sorted=[...batches].sort((a,b)=>new Date(a.expireDate)-new Date(b.expireDate));if(!sorted.length){container.innerHTML='<div class="empty-state">Belum ada batch</div>';return;}container.innerHTML=sorted.map(b=>{const item=items.find(i=>i.id===b.itemId),name=item?item.name:'Item dihapus',exp=new Date(b.expireDate),today=new Date(),daysLeft=Math.ceil((exp-today)/86400000);let status='',statusClass='';if(daysLeft<0){status='⚠️ EXPIRED';statusClass='expired';}else if(daysLeft<7){status=`⏰ ${daysLeft} hari`;statusClass='soon';}else status=`✅ ${daysLeft} hari`;return `<div class="batch-item"><div class="batch-info"><div class="batch-name">${name}</div><div class="batch-expire ${statusClass}">${b.expireDate} • ${status}</div></div><span class="batch-qty">${b.qty}</span></div>`;}).join('');}
function renderSO(){const container=document.getElementById('soList'),today=new Date().toISOString().split('T')[0],todaySO=soData.filter(s=>s.date===today).sort((a,b)=>b.id-a.id);let totalPhysical=0,totalSystem=0;todaySO.forEach(s=>{totalPhysical+=s.physical||0;totalSystem+=s.system||0;});document.getElementById('soTotalToday').textContent=todaySO.length;document.getElementById('soDiff').textContent=totalPhysical-totalSystem;if(!todaySO.length){container.innerHTML='<div class="empty-state">Belum ada SO hari ini</div>';return;}container.innerHTML=todaySO.map(s=>{const item=items.find(i=>i.id===s.itemId),name=item?item.name:'Item dihapus',diff=(s.physical||0)-(s.system||0),diffStr=diff>0?`+${diff}`:diff,diffColor=diff===0?'var(--muted)':diff>0?'var(--success)':'var(--danger)';return `<div class="so-item"><div class="so-header"><span class="so-name">${name}</span><span class="so-date">${s.note||'-'}</span></div><div class="so-detail"><span>Fisik: <strong>${s.physical||0}</strong></span><span>Sistem: <strong>${s.system||0}</strong></span><span style="color:${diffColor}">Selisih: <strong>${diffStr}</strong></span></div></div>`;}).join('');}
function renderOpenings(){const container=document.getElementById('openingList'),list=items.filter(i=>openings[i.id]!==undefined);if(!list.length){container.innerHTML='<div class="empty-state">Belum ada stock awal</div>';return;}container.innerHTML=list.map(item=>`<div class="tx-item"><div class="tx-info"><div class="tx-name">${item.name}</div><div class="tx-detail">${item.uomKecil||'UOM'}</div></div><span class="tx-qty">${openings[item.id]}</span></div>`).join('');}
function renderDraftOrders(){const container=document.getElementById('draftList');if(!draftOrders.length){container.innerHTML='<div class="empty-state">Belum ada draft order</div>';return;}container.innerHTML=draftOrders.map(d=>{const item=items.find(i=>i.id===d.itemId),name=item?item.name:'Item dihapus';return `<div class="draft-item"><div class="draft-info"><div class="draft-name">${name}</div><div class="tx-detail">Rekomendasi: ${d.qty}</div></div><button class="tx-delete" onclick="deleteDraft(${d.id})">✕</button></div>`;}).join('');}
function renderRecentActivity(){const container=document.getElementById('recentList'),all=[...transactions.map(t=>({...t,type:t.type==='IN'?'in':'out'})),...soData.map(s=>({...s,type:'so'}))].sort((a,b)=>b.id-a.id).slice(0,10);if(!all.length){container.innerHTML='<div class="empty-state">Belum ada aktivitas</div>';return;}container.innerHTML=all.map(a=>{const item=items.find(i=>i.id===a.itemId),name=item?item.name:'Item dihapus',icon=a.type==='in'?'📥':a.type==='out'?'📤':'📋',cls=a.type==='in'?'in':a.type==='out'?'out':'so',label=a.type==='in'?'IN':a.type==='out'?'OUT':'SO',detail=a.type==='so'?`Fisik: ${a.physical||0} | Sistem: ${a.system||0}`:`${a.qty} ${a.note||''}`;return `<div class="activity-item"><div class="activity-icon ${cls}">${icon}</div><div class="activity-info"><div class="activity-title">${name}</div><div class="activity-desc">${label} • ${detail}</div></div><div class="activity-time">${new Date(a.id).toLocaleDateString()}</div></div>`;}).join('');}
function renderChart(){const canvas=document.getElementById('stockChart');if(!canvas)return;const ctx=canvas.getContext('2d'),labels=items.slice(0,10).map(i=>i.name.substring(0,12)),data=items.slice(0,10).map(i=>getCurrentStock(i.id)),dpr=window.devicePixelRatio||1,rect=canvas.getBoundingClientRect();canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;ctx.scale(dpr,dpr);const width=rect.width,height=rect.height,padding=40,chartWidth=width-padding*2,chartHeight=height-padding*2,maxVal=Math.max(...data,5),barWidth=Math.min(chartWidth/data.length-4,30);ctx.clearRect(0,0,width,height);ctx.strokeStyle='#e2e8f0';ctx.lineWidth=.5;for(let i=0;i<=4;i++){const y=padding+chartHeight-(i/4)*chartHeight;ctx.beginPath();ctx.moveTo(padding,y);ctx.lineTo(width-padding,y);ctx.stroke();ctx.fillStyle='#94a3b8';ctx.font='9px sans-serif';ctx.fillText(Math.round(i/4*maxVal),4,y+3);}data.forEach((val,i)=>{const x=padding+i*(chartWidth/data.length)+(chartWidth/data.length-barWidth)/2,barHeight=val/maxVal*chartHeight,y=padding+chartHeight-barHeight;ctx.fillStyle='#3b82f6';ctx.beginPath();if(ctx.roundRect)ctx.roundRect(x,y,barWidth,barHeight,4);else ctx.rect(x,y,barWidth,barHeight);ctx.fill();ctx.fillStyle='#475569';ctx.font='8px sans-serif';ctx.textAlign='center';ctx.fillText(labels[i]||'',x+barWidth/2,height-4);});}
function populateSelects(){['inItem','outItem','soItem','estItem','openItem'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const currentVal=el.value;el.innerHTML=items.map(item=>`<option value="${item.id}">${item.name}</option>`).join('');if(currentVal)el.value=currentVal;});}
function navigateTo(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.querySelector(`#page-${page}`).classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.remove('active'));document.querySelector(`.nav-btn[onclick*="${page}"]`)?.classList.add('active');currentPage=page;}
function switchTab(tab){document.querySelectorAll('.tab-content').forEach(t=>t.classList.remove('active'));document.querySelector(`#tab-${tab}`).classList.add('active');document.querySelectorAll('.tab-btn').forEach(b=>b.classList.remove('active'));document.querySelector(`.tab-btn[onclick*="${tab}"]`).classList.add('active');}
function openModal(id){document.getElementById(id).classList.add('show');}
function closeModal(id){document.getElementById(id).classList.remove('show');}
function showToast(message,type='info'){const toast=document.getElementById('toast');toast.textContent=message;toast.className=`toast ${type}`;toast.style.display='block';clearTimeout(toast._timeout);toast._timeout=setTimeout(()=>toast.style.display='none',3000);}
function getCurrentStock(itemId){const opening=openings[itemId]||0,inTotal=transactions.filter(t=>t.itemId===itemId&&t.type==='IN').reduce((sum,t)=>sum+t.qty,0),outTotal=transactions.filter(t=>t.itemId===itemId&&t.type==='OUT').reduce((sum,t)=>sum+t.qty,0);return opening+inTotal-outTotal;}
function getBatchesForItem(itemId){return batches.filter(b=>b.itemId===itemId&&b.qty>0).sort((a,b)=>new Date(a.expireDate)-new Date(b.expireDate));}
function generateSKU(){const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';let sku='';for(let i=0;i<8;i++)sku+=chars.charAt(Math.floor(Math.random()*chars.length));return sku;}
function updateSoSystem(){const el=document.getElementById('soItem'),system=document.getElementById('soSystem');if(!el||!system)return;const itemId=parseInt(el.value);system.value=getCurrentStock(itemId);}
async function saveItem(){const name=document.getElementById('addName').value.trim(),category=document.getElementById('addCategory').value,sku=document.getElementById('addSku').value.trim()||generateSKU(),uomBesar=document.getElementById('addUomBesar').value.trim(),uomKecil=document.getElementById('addUomKecil').value.trim(),konversi=parseFloat(document.getElementById('addKonversi').value)||1,opening=parseFloat(document.getElementById('addOpening').value)||0,price=parseFloat(document.getElementById('addPrice').value)||0,displayName=document.getElementById('addDisplayName').value.trim(),image=document.getElementById('addImage').files[0];if(!name){showToast('Nama barang wajib diisi!','error');return;}if(!uomBesar||!uomKecil){showToast('UOM Besar dan Kecil wajib diisi!','error');return;}if(items.some(i=>i.sku===sku)){showToast('SKU sudah digunakan!','error');return;}let imageData='';if(image)imageData=await readFileAsDataURL(image);const newItem={id:Date.now(),name,sku,category,uomBesar,uomKecil,konversi,price,displayName:displayName||name,image:imageData,createdAt:new Date().toISOString()};await db.saveItem(newItem);items.push(newItem);if(opening>0){openings[newItem.id]=opening;await db.saveOpening({itemId:newItem.id,qty:opening});}closeModal('modal-item');renderAll();showToast('Item berhasil ditambahkan!','success');}
function readFileAsDataURL(file){return new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(file);});}
function previewImage(event){const file=event.target.files[0],container=document.getElementById('imagePreview');if(file){const reader=new FileReader();reader.onload=()=>container.innerHTML=`<img src="${reader.result}" alt="Preview">`;reader.readAsDataURL(file);}else container.innerHTML='';}
function toggleMerchFields(){const cat=document.getElementById('addCategory').value;document.getElementById('merchFields').style.display=(cat==='Merchandise'||cat==='Kitchen Supplier')?'block':'none';}
async function deleteItem(id){if(!confirm('Hapus item ini dan semua datanya?'))return;for(const b of batches.filter(b=>b.itemId===id))await db.deleteBatch(b.id);batches=batches.filter(b=>b.itemId!==id);for(const t of transactions.filter(t=>t.itemId===id))await db.deleteTransaction(t.id);transactions=transactions.filter(t=>t.itemId!==id);delete openings[id];await db.deleteOpening(id);await db.deleteItem(id);items=items.filter(i=>i.id!==id);renderAll();showToast('Item dihapus!','warning');}
async function saveIn(){const itemId=parseInt(document.getElementById('inItem').value),qty=parseFloat(document.getElementById('inQty').value),expire=document.getElementById('inExpire').value,note=document.getElementById('inNote').value.trim();if(!itemId||!qty||qty<=0){showToast('Isi semua data dengan benar!','error');return;}if(!expire){showToast('Expire Date wajib diisi!','error');return;}const tx={id:Date.now(),itemId,qty,type:'IN',note:note||'Barang masuk',date:new Date().toISOString(),expireDate:expire,batchId:Date.now()+1},batch={id:tx.batchId,itemId,qty,expireDate:expire,remaining:qty};await db.saveBatch(batch);batches.push(batch);await db.saveTransaction(tx);transactions.push(tx);closeModal('modal-in');renderAll();showToast(`Barang masuk ${qty} berhasil!`,'success');}
async function saveOut(){const itemId=parseInt(document.getElementById('outItem').value),batchId=parseInt(document.getElementById('outBatch').value),qty=parseFloat(document.getElementById('outQty').value),note=document.getElementById('outNote').value.trim();if(!itemId||!batchId||!qty||qty<=0){showToast('Isi semua data dengan benar!','error');return;}const batch=batches.find(b=>b.id===batchId);if(!batch){showToast('Batch tidak ditemukan!','error');return;}if(qty>batch.remaining){showToast(`Stok batch tidak cukup! (Sisa: ${batch.remaining})`,'error');return;}batch.remaining-=qty;batch.qty=batch.remaining;await db.saveBatch(batch);const tx={id:Date.now(),itemId,qty,type:'OUT',note:note||'Barang keluar',date:new Date().toISOString(),batchId};await db.saveTransaction(tx);transactions.push(tx);if(batch.remaining===0){await db.deleteBatch(batch.id);batches=batches.filter(b=>b.id!==batch.id);}closeModal('modal-out');renderAll();showToast(`Barang keluar ${qty} berhasil!`,'success');}
function loadOutBatches(){const itemId=parseInt(document.getElementById('outItem').value),select=document.getElementById('outBatch');select.innerHTML='<option value="">-- Pilih Batch --</option>';if(!itemId)return;const available=getBatchesForItem(itemId);if(!available.length){select.innerHTML='<option value="">Tidak ada batch tersedia</option>';return;}available.forEach(b=>{const opt=document.createElement('option');opt.value=b.id;opt.textContent=`${b.expireDate} (Sisa: ${b.remaining})`;select.appendChild(opt);});}
function updateOutUom(){const itemId=parseInt(document.getElementById('outItem').value),item=items.find(i=>i.id===itemId);document.getElementById('outUom').value=item?item.uomKecil:'';}
function updateInUom(){const itemId=parseInt(document.getElementById('inItem').value),item=items.find(i=>i.id===itemId);document.getElementById('inUom').value=item?item.uomKecil:'';}
async function saveSO(){const itemId=parseInt(document.getElementById('soItem').value),physical=parseFloat(document.getElementById('soPhysical').value),note=document.getElementById('soNote').value.trim(),date=document.getElementById('soDate').value||new Date().toISOString().split('T')[0];if(!itemId||physical<0){showToast('Isi data dengan benar!','error');return;}const system=getCurrentStock(itemId),so={id:Date.now(),itemId,physical,system,note:note||'-',date};await db.saveSO(so);soData.push(so);closeModal('modal-so');renderAll();showToast('SO berhasil disimpan!','success');}
async function setOpening(){const itemId=parseInt(document.getElementById('openItem').value),qty=parseFloat(document.getElementById('openQty').value);if(!itemId||qty<0){showToast('Isi data dengan benar!','error');return;}openings[itemId]=qty;await db.saveOpening({itemId,qty});renderAll();showToast('Stock awal diupdate!','success');}
async function deleteTransaction(id){if(!confirm('Hapus transaksi ini?'))return;const tx=transactions.find(t=>t.id===id);if(!tx)return;if(tx.type==='OUT'&&tx.batchId){const batch=batches.find(b=>b.id===tx.batchId);if(batch){batch.remaining+=tx.qty;batch.qty=batch.remaining;await db.saveBatch(batch);}}await db.deleteTransaction(id);transactions=transactions.filter(t=>t.id!==id);renderAll();showToast('Transaksi dihapus!','warning');}
async function deleteDraft(id){await db.deleteDraftOrder(id);draftOrders=draftOrders.filter(d=>d.id!==id);renderAll();}
function calculateEstimate(){const itemId=parseInt(document.getElementById('estItem').value),sales=parseFloat(document.getElementById('estSales').value)||0,safeDays=parseFloat(document.getElementById('estSafeDays').value)||7,factor=parseFloat(document.getElementById('estFactor').value)||1.1;if(!itemId)return;const item=items.find(i=>i.id===itemId);if(!item)return;const stock=getCurrentStock(itemId);document.getElementById('estCurrentStock').value=`${stock} ${item.uomKecil}`;const ads=sales/30,need=Math.ceil(ads*safeDays*factor),recommend=Math.max(0,need-stock);document.getElementById('estRecommendation').value=`${recommend} ${item.uomKecil}`;}
async function addToDraft(){const itemId=parseInt(document.getElementById('estItem').value),rec=document.getElementById('estRecommendation').value,qty=parseInt(rec.split(' ')[0])||0;if(!itemId||qty<=0){showToast('Tidak ada rekomendasi order!','error');return;}const draft={id:Date.now(),itemId,qty,createdAt:new Date().toISOString()};await db.saveDraftOrder(draft);draftOrders.push(draft);renderAll();showToast('Draft order ditambahkan!','success');}
async function syncData(){showToast('🔄 Sinkronisasi...','info');await loadAllData();renderAll();showToast('✅ Data tersinkronisasi!','success');}
function exportData(){const data={items,batches,transactions,soData,openings,draftOrders,exportedAt:new Date().toISOString()},blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`inventory_backup_${new Date().toISOString().split('T')[0]}.json`;a.click();URL.revokeObjectURL(url);showToast('📤 Data diekspor!','success');}
async function importData(event){const file=event.target.files[0];if(!file)return;try{const text=await file.text(),data=JSON.parse(text);if(!confirm('Import akan mengganti semua data saat ini. Lanjutkan?'))return;await clearAllData();for(const item of data.items||[]){await db.saveItem(item);items.push(item);}for(const batch of data.batches||[]){await db.saveBatch(batch);batches.push(batch);}for(const tx of data.transactions||[]){await db.saveTransaction(tx);transactions.push(tx);}for(const so of data.soData||[]){await db.saveSO(so);soData.push(so);}for(const [itemId,qty] of Object.entries(data.openings||{})){openings[itemId]=qty;await db.saveOpening({itemId:parseInt(itemId),qty});}for(const draft of data.draftOrders||[]){await db.saveDraftOrder(draft);draftOrders.push(draft);}renderAll();showToast('📥 Data diimport!','success');}catch(error){showToast('❌ Gagal import data!','error');console.error(error);}event.target.value='';}
async function resetAll(){if(!confirm('⚠️ Hapus SEMUA data? Tindakan ini tidak bisa dibatalkan!'))return;if(!confirm('Yakin 100%?'))return;await clearAllData();items=[];batches=[];transactions=[];soData=[];openings={};draftOrders=[];renderAll();showToast('🗑️ Semua data direset!','warning');}
async function clearAllData(){const stores=['items','batches','transactions','daily_so','openings','draft_orders'];for(const store of stores){const all=await db._getAll(store);for(const item of all)await db._delete(store,item.id);}}
function setupDateInputs(){const today=new Date().toISOString().split('T')[0];document.querySelectorAll('input[type="date"]').forEach(el=>{if(!el.value)el.value=today;});}
if(!CanvasRenderingContext2D.prototype.roundRect){CanvasRenderingContext2D.prototype.roundRect=function(x,y,w,h,r){if(w<2*r)r=w/2;if(h<2*r)r=h/2;this.moveTo(x+r,y);this.lineTo(x+w-r,y);this.quadraticCurveTo(x+w,y,x+w,y+r);this.lineTo(x+w,y+h-r);this.quadraticCurveTo(x+w,y+h,x+w-r,y+h);this.lineTo(x+r,y+h);this.quadraticCurveTo(x,y+h,x,y+h-r);this.lineTo(x,y+r);this.quadraticCurveTo(x,y,x+r,y);this.closePath();return this;};}
